name: Hello World

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello, world!"
          echo "Commit hash: ${{ github.sha }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
